version: '3'

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html:cached
      # Ajout d'un volume pour le cache Composer
      - composer_cache:/root/.composer/cache
      # Ajout d'un volume pour le cache Symfony
      - symfony_cache:/var/www/html/var/cache
      - symfony_logs:/var/www/html/var/log
    environment:
      # Optimisations PHP
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 30
      COMPOSER_MEMORY_LIMIT: -1
    networks:
      - symfony

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - symfony

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_unicode_ci
        --innodb_buffer_pool_size=256M
        --table_definition_cache=400
        --performance_schema=OFF
    volumes:
      - mysql_data:/var/lib/mysql:cached
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 64M
    depends_on:
      - mysql
    networks:
      - symfony

  # Nouveau service pour les emails
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Interface web
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  mysql_data:
  composer_cache:
  symfony_cache:
  symfony_logs: 